### ISSUE TITLE
RPC 模块支持与java跨平台进行通信吗

### ISSUE THREAD

**Issue by DayDreamLen** [vnpy/vnpy_rpcservice#6]
RPC模块无法与java跨平台通信  收到的数据为乱码

**Comment by DayDreamLen** [comment]
Check your email for a link to reset your password. If it doesn’t appear within a few minutes, check your spam folder.

**Comment by vnpy** [comment]
不支持，vnpy.rpc底层使用的是Python的pickle序列化协议，Java上应该不支持了
